import Head from 'next/head'
import Layout from '../components/layout';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'antd';
import 'antd/dist/antd.css';
import {
  ApolloClient,
  InMemoryCache,
  gql
} from "@apollo/client";


export async function getStaticProps() {

  const client = new ApolloClient({
    uri: "http://localhost:3200/graphql",
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql `
      query getPredio {
        allPredios {
          nodes {
            idPredio
            nombre
            departamento
            municipio
            avaluo
          }
        }
      }
    `,
  });
  console.log("data", data.allPredios.nodes);

  return {
    props: {
      predios: data.allPredios.nodes,
    },
  };
};

export default function Home({ predios }) {
  return ( <
    div >
    <
    Layout > < /Layout> <
    Head >
    <
    title > Catastro < /title> <
    meta name = "description"
    content = "Generated by create next app" / >
    <
    link rel = "icon"
    href = "/favicon.ico" / >
    <
    /Head> <
    main className = { styles.main } >

    <
    h1 className = { styles.title } >
    Welcome to < a href = "https://nextjs.org" > Catastro municipal! < /a> <
    /h1>

    <
    p className = { styles.description } >
    Get started by editing { ' ' } <
    code className = { styles.code } > pages / index.js < /code> <
    /p> <
    div className = { styles.nav } >
    <
    Button type = "primary"
    shape = "round"
    size = "large"
    href = "/predio/crearPredio" > Crear predio < /Button> <
    /div> <
    div className = { styles.grid } > {
      predios.map((predios) => ( <
        a key = { predios.idPredio }
        href = { `/predio/${predios.idPredio}` }
        className = { styles.card } >
        <
        h2 className = { styles.color } > { predios.nombre } < /h2> <
        h2 className = { styles.color } > Predial: { predios.idPredio } < /h2> <
        p > < strong > Departamento: < /strong>{predios.departamento}</p >
        <
        p > < strong > Municipio: < /strong>{predios.municipio}</p >
        <
        /a>
      ))
    } <
    /div>

    <
    /main>

    <
    footer className = { styles.footer } >
    <
    a href = "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    target = "_blank"
    rel = "noopener noreferrer" >
    Powered by { ' ' } <
    span className = { styles.logo } >
    <
    Image src = "/vercel.svg"
    alt = "Vercel Logo"
    width = { 72 }
    height = { 16 }
    /> <
    /span> <
    /a> <
    /footer> <
    /div>
  )
}